# Generated by Django 4.2.3 on 2023-07-27 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Имя покупателя')),
                ('item', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название камня')),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма сделки')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество товара')),
                ('date', models.DateTimeField(verbose_name='Дата и время сделки')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='sales.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-customer'],
            },
        ),
    ]
